name: CI-CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
  
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: giahao07092001
          password: giahao098
      
      - name: Build Docker Image
        run: docker build -t giahao07092001/mycv .

      - name: Pulish image to docker hub
        run: docker push giahao07092001/mycv:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull image from docker hub
        run: docker pull giahao07092001/mycv:latest
      - name: Delete old container
        run: docker run -d -p 8080:8080 --name mycvContainer giahao07092001/mycv